base_dir_local: C:\Users\ScipioneFrancesco\polybox - Francesco Scipione (francesco.scipione@protonmail.ch)@polybox.ethz.ch\01_Inspire\01_Projects\01_Via_Integrity\02_Code\prochain_transformer\
base_dir_cluster: /cluster/home/fscipion/prochain_transformer/
project_name: ProChain Transformer
version: 1.0.0